import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [signature, setSignature] = useState<String>("Name");
  const [date, setDate] = useState("Date");
  const [content, setContent] = useState("Content");
  return (
    <>
      <Head>
        <title>Signature</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="header">
          <h1>Signature</h1>
        </div>
        <div className="container">
          <div className="display">
            <div className="display-header">
              <p className="sign">{signature}</p>
              <p className="display-date">{date}</p>
            </div>
            <p className="display-content">{content}</p>
          </div>
          <div className="inputs">
            <label htmlFor="signature">Signature</label>
            <input
              type="text"
              name="signature"
              id="signature"
              onChange={(e: any) => setSignature(e.target.value)}
            />

            <label htmlFor="date">Date</label>
            <input
              type="date"
              name="date"
              id="date"
              onChange={(e: any) => setDate(e.target.value)}
            />

            <label htmlFor="content">Content</label>
            <textarea
              name="content"
              id="content"
              onChange={(e: any) => setContent(e.target.value)}
            ></textarea>
          </div>
        </div>
      </main>
    </>
  );
}
